"""empty message

Revision ID: 3554f41648e2
Revises: fde8e14f8a27
Create Date: 2022-08-06 18:23:44.878318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3554f41648e2'
down_revision = 'fde8e14f8a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True, insert_after='id'))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True, insert_after='address'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
